import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import fs from "fs/promises";
import path from "path";
import crypto from "crypto";

import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { createAuditLog } from "@/lib/admin/audit-log";
import {
    FAVICON_MAX_BYTES,
    detectFaviconExtension,
    extensionForFaviconMime,
    faviconFilenameFromUrl,
    getFaviconPublicUrl,
    getFaviconStorageDir,
} from "@/lib/store-favicon";

export const runtime = "nodejs";

/**
 * ==========================================
 * ADMIN FAVICON MANAGEMENT
 * ==========================================
 *
 * POST   /api/admin/settings/favicon  → upload/replace
 * DELETE /api/admin/settings/favicon  → remove (reset to default)
 *
 * Reuses the project's existing local upload storage
 * (`storage/uploads/...` + a route handler that serves it),
 * exactly like product images. Only the public URL is written
 * to `StoreSetting.faviconUrl`.
 *
 * Security:
 *   - ADMIN session required (server-side, not just hidden UI)
 *   - file size, client MIME, extension AND magic bytes checked
 *   - the stored file name is generated by the server
 *   - the previous file is removed only when it lives in our
 *     own favicon storage directory
 */

/** Session ADMIN yang valid, atau null. */
async function getAdminUserId(): Promise<string | null> {
    const session = await auth();

    if (!session?.user) {
        return null;
    }

    if (
        (session.user as { role?: string }).role !==
        "ADMIN"
    ) {
        return null;
    }

    return session.user.id ?? null;
}

/**
 * Best-effort removal of a previously stored favicon.
 * Never throws: failing to clean up an old file must not
 * fail the admin action.
 */
async function removeStoredFavicon(
    url: string | null | undefined
) {
    const filename = faviconFilenameFromUrl(url);

    if (!filename) {
        return;
    }

    try {
        await fs.unlink(
            path.join(getFaviconStorageDir(), filename)
        );
    } catch {
        // Already gone / not present — nothing to do.
    }
}

export async function POST(request: Request) {
    try {
        const adminId = await getAdminUserId();

        if (!adminId) {
            return NextResponse.json(
                {
                    success: false,
                    message: "Unauthorized.",
                },
                { status: 401 }
            );
        }

        let formData: FormData;

        try {
            formData = await request.formData();
        } catch {
            return NextResponse.json(
                {
                    success: false,
                    message: "Gagal membaca form data.",
                },
                { status: 400 }
            );
        }

        const file = formData.get("file");

        if (!(file instanceof File)) {
            return NextResponse.json(
                {
                    success: false,
                    message: "File favicon wajib diupload.",
                },
                { status: 400 }
            );
        }

        if (file.size === 0) {
            return NextResponse.json(
                {
                    success: false,
                    message: "File favicon kosong.",
                },
                { status: 400 }
            );
        }

        if (file.size > FAVICON_MAX_BYTES) {
            return NextResponse.json(
                {
                    success: false,
                    message: "Ukuran favicon maksimal 1MB.",
                },
                { status: 400 }
            );
        }

        /*
         * The browser MIME is attacker-controlled, so it is only
         * used as a first filter. The authoritative decision is
         * made from the magic bytes below.
         */
        const declaredMime = file.type || "";
        const declaredExtension =
            extensionForFaviconMime(declaredMime);

        if (declaredMime && !declaredExtension) {
            return NextResponse.json(
                {
                    success: false,
                    message:
                        "Format favicon harus PNG, JPG, WEBP, atau ICO.",
                },
                { status: 400 }
            );
        }

        const buffer = Buffer.from(
            await file.arrayBuffer()
        );

        if (buffer.length > FAVICON_MAX_BYTES) {
            return NextResponse.json(
                {
                    success: false,
                    message: "Ukuran favicon maksimal 1MB.",
                },
                { status: 400 }
            );
        }

        const detectedExtension =
            detectFaviconExtension(buffer);

        if (!detectedExtension) {
            return NextResponse.json(
                {
                    success: false,
                    message:
                        "File bukan gambar favicon valid (PNG/JPG/WEBP/ICO).",
                },
                { status: 400 }
            );
        }

        /*
         * When the browser did declare a supported type, it must
         * agree with the real content. This blocks a PNG renamed
         * to `.ico` (and vice versa) from being stored under a
         * misleading extension.
         */
        if (
            declaredExtension &&
            declaredExtension !== detectedExtension
        ) {
            return NextResponse.json(
                {
                    success: false,
                    message:
                        "Isi file tidak cocok dengan format yang dipilih.",
                },
                { status: 400 }
            );
        }

        const uploadDir = getFaviconStorageDir();

        await fs.mkdir(uploadDir, {
            recursive: true,
        });

        const randomName = crypto
            .randomBytes(16)
            .toString("hex");

        const fileName = `${Date.now()}-${randomName}.${detectedExtension}`;

        await fs.writeFile(
            path.join(uploadDir, fileName),
            buffer
        );

        const url = getFaviconPublicUrl(fileName);

        const previous = await prisma.storeSetting.findUnique(
            {
                where: { id: 1 },
                select: { faviconUrl: true },
            }
        );

        await prisma.storeSetting.upsert({
            where: { id: 1 },
            create: {
                id: 1,
                storeName: "",
                address: "",
                faviconUrl: url,
            },
            update: {
                faviconUrl: url,
            },
        });

        if (previous?.faviconUrl !== url) {
            await removeStoredFavicon(
                previous?.faviconUrl
            );
        }

        await createAuditLog({
            adminId,
            action: "STORE_FAVICON_UPDATED",
            entityType: "StoreSetting",
            entityId: 1,
            description:
                "Favicon website diperbarui.",
            metadata: { faviconUrl: url },
        });

        /*
         * The favicon is part of the root layout metadata, which
         * is baked into every prerendered route. Revalidate the
         * root layout so the new icon applies everywhere without
         * a rebuild (same mechanism the settings PUT already uses).
         */
        revalidatePath("/", "layout");

        return NextResponse.json(
            {
                success: true,
                message:
                    "Favicon berhasil diperbarui.",
                url,
                data: { url },
            },
            { status: 201 }
        );
    } catch (error) {
        console.error("FAVICON UPLOAD ERROR:", error);

        return NextResponse.json(
            {
                success: false,
                message: "Gagal mengupload favicon.",
            },
            { status: 500 }
        );
    }
}

export async function DELETE() {
    try {
        const adminId = await getAdminUserId();

        if (!adminId) {
            return NextResponse.json(
                {
                    success: false,
                    message: "Unauthorized.",
                },
                { status: 401 }
            );
        }

        const previous = await prisma.storeSetting.findUnique(
            {
                where: { id: 1 },
                select: { faviconUrl: true },
            }
        );

        await prisma.storeSetting.upsert({
            where: { id: 1 },
            create: {
                id: 1,
                storeName: "",
                address: "",
                faviconUrl: null,
            },
            update: {
                faviconUrl: null,
            },
        });

        await removeStoredFavicon(
            previous?.faviconUrl
        );

        await createAuditLog({
            adminId,
            action: "STORE_FAVICON_REMOVED",
            entityType: "StoreSetting",
            entityId: 1,
            description:
                "Favicon website dihapus (kembali ke default).",
        });

        revalidatePath("/", "layout");

        return NextResponse.json({
            success: true,
            message:
                "Favicon dihapus, kembali ke ikon default.",
            url: null,
        });
    } catch (error) {
        console.error(
            "FAVICON REMOVE ERROR:",
            error
        );

        return NextResponse.json(
            {
                success: false,
                message: "Gagal menghapus favicon.",
            },
            { status: 500 }
        );
    }
}
